services:
  - type: web
    name: sweatbox-apg
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase: false
        sync: false
      - key: TELEGRAM_CHAT_ID
        fromDatabase: false
        sync: false
      - key: ADMIN_USERNAME
        fromDatabase: false
        sync: false
      - key: ADMIN_PASSWORD
        fromDatabase: false
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
